---
############
#Modify objects
############

- include: bigip_virtual_server/manage_vip.yml 
  vars:
    - name: "ansible_demo_vip" 
    - all_rules: "ansible_demo_rewrite"
  when: state == "present"

...
